### ISSUE TITLE
Problem while ssvmup build

### ISSUE THREAD

**Issue by feeva** [second-state/ssvm-nodejs-starter#2] opened 2020-07-19 14:25 UTC
I got this:

[report-8b07f8e5-1661-4aea-ad5f-7a74411660f1.toml.txt](https://github.com/second-state/ssvm-nodejs-starter/files/4943827/report-8b07f8e5-1661-4aea-ad5f-7a74411660f1.toml.txt)

```
dylan@mars-abc
:~/hello$ ssvmup build
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.06s
:-) [WARN]: origin crate has no README
[INFO]: Installing wasm-bindgen...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "no ssvm mapping for bindgen 0.2.65" }', src/install/mod.rs:149:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Well, this is embarrassing.

ssvmup had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/tmp/report-8b07f8e5-1661-4aea-ad5f-7a74411660f1.toml". Submit an issue or email with the subject of "ssvmup Crash Report" and include the report as an attachment.

- Authors: wangshishuo

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
```

**Comment by juntao** [comment] 2020-07-19 15:47
Hi Dylan,

At this time, ssvmup requires a specific version of wasm-bindgen. Here is the line needed in your Cargo.toml:

wasm-bindgen = "=0.2.61"

See:

https://github.com/second-state/ssvm-nodejs-starter/blob/master/Cargo.toml

We need a better error message. But please bear with us for now. Thanks.

**Comment by juntao** [comment] 2020-07-21 23:24
I am closing this one now. If the problem is not fixed, please re-open it and let us now.

**Closed as completed by juntao** 2020-07-21 23:24 UTC

**Comment by feeva** [comment] 2020-07-22 16:40
So I changed this:

    wasm-bindgen = "0.2.61"

to this:

    wasm-bindgen = "=0.2.61"

Built successfully. Thanks
